#!/usr/bin/env python3

import os
import re
import sys

# ; This file is automatically created by ../../tests/scripts/AssemblerOutputTest.py from test.txt.
header_re = re.compile(r"(; This file is automatically created by )(.*)( from .*)")

with open(sys.argv[1], "r") as f:
    for line in f:
        match = header_re.match(line)
        if match:
            tool_name = match.group(2)
            tool_name = os.path.basename(tool_name)
            line = f"{match.group(1)}{tool_name}{match.group(3)}\n"
        print(line, end="")
